# ProjectOS HomeAPI Configuration File

debug: false
# Device definition for the local network
devices:
  - name: "My Computer"
    id: "my-computer"
    type: "computer"
    mac: "00:00:00:00:00:00"
    ip: "0.0.0.0"
  - name: "My Router"
    id: "my-router"
    type: "router"
    mac: "00:00:00:00:00:00"
    ip: "0.0.0.0"
# DDNS configuration with Cloudflare
dns:
  domain: "mydomain.com"
  subdomain: "home"
  token: "mytoken"