# Template repo: https://github.com/FedericoPonzi/rust-ci
name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Compile
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target:
          #- aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf 
          - i686-unknown-linux-gnu
          #- i686-unknown-linux-musl
          #- arm-unknown-linux-gnueabi
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}


      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Move
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release          
          mv projectos-local_api ~/projectos-local_api-${{ matrix.target }}
          cd -
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            ~/projectos-local_api-${{ matrix.target }}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'projectos-local_api*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
